spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.28.7:3306/6miles?useUnicode=true&useJDBCCompliantTimezoneShift=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  redis:
    host: 182.92.210.231
    port: 6379
    password: root

swagger:
  show: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
